// Generated by CoffeeScript 1.6.3
(function() {
  var AutocompleteBox;

  if (window.$ == null) {
    window.$ = require("jquery-commonjs");
  }

  AutocompleteBox = require("../lib/autocompletebox");

  module.exports = function() {
    var $fake, $orig, setup;
    QUnit.module("AutocompleteBox");
    $orig = null;
    $fake = null;
    setup = function(options, attrs) {
      if (options == null) {
        options = [];
      }
      if (attrs == null) {
        attrs = "";
      }
      $orig = $("<select class=\"reform-autocompletebox\" " + attrs + ">" + (options.map(function(opt) {
        return "<option value=\"" + opt.value + "\">" + opt.text + "</option>";
      }).join("")) + "</select>");
      $orig.appendTo("#qunit-fixture");
      new AutocompleteBox($orig.get(0));
      return $fake = $orig.parent();
    };
    test("The fake wraps the original", 1, function() {
      setup();
      return ok($fake.is(".reform-autocompletebox-fake"), "Parent should be the fake");
    });
    return test("Title input created", 1, function() {
      setup();
      return ok($fake.find(':first-child').hasClass("reform-autocompletebox-input"), "Fake should have title input");
    });
  };

}).call(this);
