// Generated by CoffeeScript 1.4.0
(function() {

  require("./checkbox_test")();

  require("./selectbox_test")();

  require("./autocompletebox_test")();

  require("./autocompletecombobox_test")();

}).call(this);
