// Generated by CoffeeScript 1.3.1
(function() {
  var CheckBox, Reform, SelectBox;

  if (window.$ == null) {
    window.$ = require("jquery-commonjs");
  }

  CheckBox = require("./checkbox");

  SelectBox = require("./selectbox");

  Reform = (function() {

    Reform.name = 'Reform';

    function Reform() {}

    Reform.prototype.process = function(node) {
      var cls, control, n, _ref, _results;
      _ref = Reform.controls;
      _results = [];
      for (cls in _ref) {
        control = _ref[cls];
        _results.push((function() {
          var _i, _len, _ref1, _results1;
          _ref1 = $(node).parent().find("." + cls);
          _results1 = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            n = _ref1[_i];
            _results1.push(new control(n));
          }
          return _results1;
        })());
      }
      return _results;
    };

    Reform.prototype.observe = function() {
      var _this = this;
      $(document).on("ready", function() {
        return _this.process("body");
      });
      return $(document).on("DOMNodeInserted", function(e) {
        return _this.process(e.target);
      });
    };

    return Reform;

  })();

  Reform.controls = {
    "reform-checkbox": CheckBox,
    "reform-selectbox": SelectBox
  };

  module.exports = Reform;

}).call(this);
