// Generated by CoffeeScript 1.6.3
(function() {
  var SelectBox,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if (window.$ == null) {
    window.$ = require("jquery-commonjs");
  }

  SelectBox = (function() {
    function SelectBox(select) {
      var _this = this;
      this.select = select;
      this.refresh = __bind(this.refresh, this);
      this.close = __bind(this.close, this);
      this.open = __bind(this.open, this);
      this.options = __bind(this.options, this);
      this.orig = $(this.select);
      if (this.orig.is(".reformed")) {
        return;
      }
      this.body = $("body");
      this.fake = $("<div/>");
      this.fake.attr("tabindex", 0);
      this.fake.attr("class", this.orig.attr("class"));
      this.orig.hide().attr("class", "reformed");
      this.fake.removeClass("reform-selectbox").addClass("reform-selectbox-fake");
      if (this.orig.is(":disabled")) {
        this.fake.addClass("disabled");
      }
      this.refresh();
      this.orig.after(this.fake).appendTo(this.fake);
      this.fake.on("keyup", function(ev) {
        if (ev.keyCode === 27) {
          ev.preventDefault();
          return ev.stopPropagation();
        }
      });
      this.fake.on("keydown", function(ev) {
        var $current, $item, $nextItem, done, goDown, goUp, itemDoesNotExist, itemIsDisabled;
        ev.preventDefault();
        ev.stopPropagation();
        if (_this.orig.is("[multiple]")) {
          return;
        }
        _this.fake.focus();
        goUp = ev.keyCode === 38;
        goDown = ev.keyCode === 40;
        if (goUp || goDown) {
          if (_this.floater == null) {
            return _this.open();
          } else {
            $current = $('.hover', _this.floater).length === 0 ? $('.selected', _this.floater) : $('.hover', _this.floater);
            if (goUp) {
              $nextItem = $current.prev().length === 0 ? $current.parent().children().last() : $current.prev();
            } else {
              $nextItem = $current.next().length === 0 ? $current.parent().children().first() : $current.next();
            }
            _this.hover($nextItem);
            return _this.scrollTo($nextItem);
          }
        } else if (ev.keyCode === 13) {
          $item = $(_this.floater).find('.hover');
          itemDoesNotExist = $item.length === 0;
          itemIsDisabled = $item.is(".disabled");
          if (itemDoesNotExist || itemIsDisabled) {
            return;
          }
          $item.siblings().andSelf().removeClass("selected");
          $item.addClass("selected");
          _this.orig.val(_this.value()).trigger("change");
          return _this.close();
        } else if (ev.keyCode === 27) {
          if (_this.floater != null) {
            return _this.close();
          }
        } else {
          done = false;
          return _this.$list.children().each(function(i, item) {
            if (!done) {
              if ($(item).text().charAt(0).toLowerCase() === String.fromCharCode(ev.keyCode).toLowerCase()) {
                done = true;
                _this.hover($(item));
                return _this.scrollTo($(item));
              }
            }
          });
        }
      });
      this.floater = null;
      this.fake.on("click", function(e) {
        if (_this.orig.is(":disabled")) {
          return;
        }
        e.stopPropagation();
        if (_this.floater === null) {
          return _this.open();
        } else {
          return _this.close();
        }
      });
      this.fake.on("mousedown", function(e) {
        return e.preventDefault();
      });
      this.orig.on("reform.sync change DOMSubtreeModified", this.refresh);
      this.body.on("reform.open", function(e) {
        if (e.target !== _this.select) {
          return _this.close();
        }
      });
      $('.reform-selectbox-options').remove();
    }

    SelectBox.prototype.hover = function($item) {
      $item.siblings().andSelf().removeClass("hover");
      return $item.addClass("hover");
    };

    SelectBox.prototype.scrollTo = function($item) {
      var $container, newScrollTop, scrollTop,
        _this = this;
      $container = $item.parent();
      newScrollTop = $item.offset().top - $container.offset().top + $container.scrollTop();
      this.ignoreMouse = true;
      if (newScrollTop > ($container.outerHeight() - $item.outerHeight())) {
        scrollTop = newScrollTop - $container.outerHeight() + $item.outerHeight();
        $container.scrollTop(scrollTop);
      } else {
        $container.scrollTop(0);
      }
      if (this.to) {
        clearTimeout(this.to);
      }
      return this.to = setTimeout(function() {
        return _this.ignoreMouse = false;
      }, 500);
    };

    SelectBox.prototype.options = function() {
      var _this = this;
      if (this.floater == null) {
        return;
      }
      this.fake.focus();
      this.floater.empty();
      this.$list = $("<div/>").appendTo(this.floater);
      this.$list.attr("class", "reform-selectbox-list");
      return this.orig.find("option").each(function(i, option) {
        var $item, $option;
        $option = $(option);
        $item = $("<div/>");
        $item.attr("class", "reform-selectbox-item");
        if ($option.is(":selected")) {
          $item.addClass("selected");
        }
        if ($option.is(":disabled")) {
          $item.addClass("disabled");
        }
        $item.attr("title", $option.attr("title"));
        $item.attr("value", $option.val());
        $item.text($option.text());
        $item.appendTo(_this.$list);
        $item.on("mousedown", function(e) {
          return e.preventDefault();
        });
        $item.hover(function() {
          if (!_this.ignoreMouse) {
            return _this.hover($item);
          }
        });
        return $item.on("click", function(e) {
          if ($item.is('.disabled')) {
            return;
          }
          if (_this.orig.is("[multiple]")) {
            $item.toggleClass("selected");
            e.stopPropagation();
          } else {
            $item.siblings().andSelf().removeClass("selected");
            $item.addClass("selected");
          }
          return _this.orig.val(_this.value()).trigger("change");
        });
      });
    };

    SelectBox.prototype.value = function() {
      return this.$list.find(".reform-selectbox-item.selected").map(function() {
        return $(this).val();
      });
    };

    SelectBox.prototype.open = function() {
      var $window, pos;
      this.orig.trigger("reform.open");
      this.floater = $("<div/>");
      this.floater.attr("class", "reform-selectbox-options");
      this.floater.css("min-width", this.fake.outerWidth());
      this.floater.addClass(this.orig.data("options-class"));
      this.body.append(this.floater);
      this.options();
      this.body.one("click", this.close);
      pos = this.fake.offset();
      this.floater.show();
      $window = $(window);
      if (pos.top + this.floater.outerHeight() > $window.height()) {
        pos.top = pos.top - this.floater.outerHeight() + this.fake.outerHeight();
      }
      if (pos.left + this.floater.outerWidth() > $window.width()) {
        pos.left = pos.left - this.floater.outerWidth() + this.fake.outerWidth();
      }
      return this.floater.css(pos);
    };

    SelectBox.prototype.close = function() {
      var _ref;
      if ((_ref = this.floater) != null) {
        _ref.remove();
      }
      return this.floater = null;
    };

    SelectBox.prototype.refresh = function() {
      var plural, selected, title;
      this.fake.toggleClass("disabled", this.orig.is(":disabled"));
      title = this.orig.data('title');
      if (!title) {
        selected = this.orig.find("option").filter(function() {
          return this.selected && $(this).data("count-option") !== "no";
        });
        plural = this.orig.data("plural");
        title = (plural != null) && selected.length > 1 ? "" + selected.length + " " + plural : selected.map(function() {
          return $(this).text();
        }).get().join(", ");
        if (!title) {
          title = this.orig.attr("title");
        }
        if (title == null) {
          title = "Select";
        }
      }
      this.fake.contents().filter(function() {
        return this.nodeType === Node.TEXT_NODE;
      }).remove();
      this.fake.append(document.createTextNode(title));
      return this.options();
    };

    return SelectBox;

  })();

  module.exports = SelectBox;

}).call(this);
